# Generated by Django 3.2.15 on 2022-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
