# Generated by Django 4.2.3 on 2025-02-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_winnerselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_away',
            name='week_number',
            field=models.IntegerField(),
        ),
    ]
