# Generated by Django 4.2.3 on 2025-02-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_home_away_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerpick',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
