# Generated by Django 4.2.3 on 2025-03-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_winnerpick_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='actual_winner',
            field=models.CharField(choices=[('Away', 'Away'), ('Home', 'Home')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='player',
            field=models.CharField(choices=[('Mom', 'Mom'), ('Mr. C.', 'Mr. C.'), ('Tiara', 'Tiara')], default='Mr. C.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='selected_pick',
            field=models.CharField(choices=[('Away', 'Away'), ('Home', 'Home')], max_length=250, null=True),
        ),
    ]
